name: CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Trigger Render Deploy
        run: curl -X POST https://api.render.com/deploy/srv-d1lspd2li9vc73eb65e0?key=BKlQTrnxze4
