spring.application.name=HRMS
server.port=${PORT:9090}
server.address=0.0.0.0
# Supabase PostgreSQL Database settings
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&stringtype=unspecified
spring.datasource.username=postgres.ybrxwadhjipdkhjodath
spring.datasource.password=Anmol@09JUL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#for dev only for prod we will have env variable for a secret key
jwt.secret=jsvdbhjvbsdibisdbiygbvadibjfeautgfeyiifeapioqponbfhbjbzdknmbbhvzmzvmbzmbnzbhvdbhvdkkb
web.client.id=951205237744-fdrp8dr4ek5ubnvkjekivo85pd31obm7.apps.googleusercontent.com

##java mail sender
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=vikashgorai985276@gmail.com
#spring.mail.password=qjtiwmkhdizsllgx
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
#spring.mail.protocol=smtp

logging.level.org.springframework.security=TRACE

#filesize(image)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

#1 hour connected if no activity
spring.websocket.timeout=3600000


